export const ADICIONAR_TAREFA = "ADICIONAR_TAREFA";
export const EDITAR_TAREFA = "EDITAR_TAREFA";
export const EXCLUIR_TAREFA = "EXCLUIR_TAREFA";
export const DEFINIR_TAREFAS = "DEFINIR_TAREFA";

export const ADICIONAR_PROJETO = "ADICIONAR_PROJETO";
export const EDITAR_PROJETO = "EDITAR_PROJETO";
export const EXCLUIR_PROJETO = "EXCLUIR_PROJETO";
export const DEFINIR_PROJETOS = "DEFINIR_PROJETOS";
export const NOTIFICAR = "NOTIFICAR";
